# Версия docker-compose
version: '3'

# Список наших сервисов (контейнеров)
services:
  php:
    # у нас свой образ для PHP, указываем путь к нему и говорим что его надо собрать
    build: ./images/php
    networks:
    - backend
    volumes:
    - /var/www/google/:/var/www/google/
  apache:
    build: ./images/apache
    depends_on:
    - php
    - db
    networks:
    - frontend
    - backend
    ports:
    - "8080:80"
    volumes:
    - /var/www/google/public/:/var/www/google/public/

  db:
    build: ./images/mysql
    ports:
    - "3306:3306"
    volumes:
    - ./databases:/var/lib/mysql
    networks:
    - backend
    # задаем пароль для root пользователя
    environment:
      MYSQL_ROOT_PASSWORD: 1
  redis:
    build: ./images/redis
    ports:
    - "6379:6379"
  laravel-echo-server:
    build:
      context: ./images/laravel-echo-server
    volumes:
    - ./images/laravel-echo-server/laravel-echo-server.json:/app/laravel-echo-server.json:ro
    ports:
    - "6001:6001"
    links:
    - redis
    - apache

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.3
    environment:
    - discovery.type=single-node
    - http.host=0.0.0.0
    - transport.host=127.0.0.1
    - xpack.security.enabled=false
    - ES_JAVA_OPTS=-Xms750m -Xmx750m
    volumes:
    - ./images/elasticsearch/esdata:/usr/share/elasticsearch/data
    - ./images/elasticsearch/esdata2:/usr/share/elasticsearch/logs
    expose:
    - "9200"
    ports:
    - "9200:9200"

networks:
  frontend:
  backend: